---
- name: create conf dirs
  file:
    path: "{{kafka_conf_dir}}_{{ item.broker_id }}/config"
    state: directory
    mode: 0755
    owner: "{{ kafka_user }}"
    group: "{{ kafka_user }}"
  with_items:
    - "{{ broker_settings }}"

- name: create log dirs
  file:
    path: "{{kafka_log_dir}}{{ item.broker_id }}"
    state: directory
    mode: 0755
    owner: "{{ kafka_user }}"
    group: "{{ kafka_user }}"
  with_items:
    - "{{ broker_settings }}"

- name: create data dirs
  file:
    path: "{{kafka_data_dir}}{{ item.broker_id }}"
    state: directory
    mode: 0755
    owner: "{{ kafka_user }}"
    group: "{{ kafka_user }}"
  with_items:
    - "{{ broker_settings }}"
